library(openai)
library(tidyverse)
library(tippy)
library(gridExtra)

###################################################
# Global variables
###################################################

uploaded_data <- "Upload" 
min_query_length <- 10  # minimum # of characters
max_query_length <- 500 # max # of characters
language_model <- "text-davinci-003"
pdf(NULL)
#' Move an element to the front of a vector
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param v is the vector
#' @param e is the element
#'
#' @return Returns a reordered vector
move_front <- function(v, e){
  ix <- which(v == e)

  # if found, move to the beginning.
  if(length(ix) != 0) {
    v <- v[-ix]
    v <- c(e, v)
  }
  return(v)
}


#' Prepare User input.
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param txt A string that stores the user input.
#' @param selected_data Name of the dataset.
#'
#' @return Returns a cleaned up version, so that it could be sent to GPT.
prep_input <- function(txt, selected_data){
  # if too short, do not send. 
  if(nchar(txt) < min_query_length || nchar(txt) > max_query_length) {
    return(NULL)
  }

  if(!is.null(selected_data)) {
    if(selected_data == uploaded_data) {
      selected_data <- "df"
    }
    txt <- paste("Use the", selected_data, "data frame. ", txt)
  }
  txt <- paste("Generate R code, not R Markdown. ", txt)

  # If the last character is not a stop, add it. 
  # Otherwise, GPT3 will add a sentence.

  # The following 5 lines were generated by ChatGPT!!!!!
  # Check if the last character is not a period
  if(substr(txt, nchar(txt), nchar(txt)) != ".") {
    # If the last character is not a period, add a period to the end of the string
    txt <- paste(txt, ".", sep = "")
  }

  return(txt)
}


#' Clean up R commands generated by GTP
#'
#' The response from GTP3 sometimes contains strings that are not R commands.
#'
#' @param cmd A string that stores the completion from GTP3.
#' @param selected_data, name of the selected dataset. 
#' @return Returns a cleaned up version, so that it could be executed as R command.
clean_cmd <- function(cmd, selected_data){
  # simple way to check
  if(grepl("That model is currently overloaded with other requests.|Error:", cmd)) {
    return(NULL)
  }
  # Use cat to converts \n to newline
  # use capture.output to get the string
  cmd <- capture.output(
    cat(cmd)
  )

  #cmd is a vector. Each element is a line.

  # sometimes it returns RMarkdown code.
  cmd <- gsub("```", "", cmd)

  # remove empty lines
  cmd <- cmd[cmd != ""]

  # replace install.packages by "#install.packages"
  cmd <- gsub("install.packages", "#install.packages", cmd)

  # if data is uploaded, add a line to get the data.
  if(selected_data == uploaded_data) {
    cmd <- c("df <- user_data()", cmd)
  }

  return(cmd)

}


###################################################################
# Prepare data
###################################################################
demos <- c(
  'Example requests:' = 'Example requests',

  'Boxplot ggplot2' = "Use ggplot2 to create a boxplot of hwy vs. class. Color by class.",
  'Boxplot in Base R' = "Create a boxplot of cty vs. class.",
  Scatter = "Use ggplot2. Plot hwy vs. cty, colored by class. Change shape by drv.",
  ANOVA = "Conduct ANOVA of hwy by class.",
  Boxplot2 = "Use ggplot2 to create a boxplot of hwy vs. class.  Color by class.
Add jitter.
Remove x label.",
  ANOVA2 = "Conduct ANOVA of log-transformed hwy by class and drv.",
  Correlation = "Create a correlation map of all the columns that contain numbers.",
  Barplot = "Calculate average cty by year and class.
Then use ggplot2 to create a barplot of average mpg by class,
colored by year. The years should be side by side.",
  Analysis = "Calculate the correlation of cty vs hwy.
Repeat that after log transformation.
Collect these results and show them.",
Analysis2 = "Only keep cars with hwy bigger than 15, but less than 40.
Add 0.5 to cty.
Perform log transformation on cty.
Raise hwy to the second power.
Calculate correlation coefficient of transformed hwy and cty.",
Analysis_complex = "hwy and cty represent miles per gallon (MPG) on the highway and in the city, respectively.
Only keep cars more efficient than 15 MPG, but less than 40, on the highway.
Add 0.5 to city MPG for correction.
Perform log transformation on city MPG.
Raise highway MPG to the second power.
Calculate correlation coefficient of  the two transformed variables.",
Neural_net = "Build a neural network model to predict 
hwy based on displ, cyl, and class.  
Use the nnet package. Plot the residules."
)

# prepare a list of available data sets.
datasets <- data()$results[, 3] # name of datasets
datasets <- gsub(" .*", "", datasets)
datasets <- move_front(datasets, "state.x77")
datasets <- move_front(datasets, "iris")
datasets <- move_front(datasets, "mtcars")
datasets <- move_front(datasets, "diamonds")
datasets <- move_front(datasets, "mpg")

# if dataset is not data frame or matrix, remove.
ix <- sapply(
  datasets, 
  function(x) {
    eval(
      parse(
        text = paste(
          "is.data.frame(",
          x,
          ") | is.matrix(",
           x, 
           ")"
        )
      )
    )
  }
)

datasets <- datasets[which(ix)]

# append a dummy value, used when user upload their data.
datasets <- c(datasets, uploaded_data)

# Generated by ChatGPT
jokes <- c(
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why was the belt arrested? Because it held up a pair of pants.",
  "Why was the math book sad? Because it had too many problems.",
  "Why was the statistician's favorite method of transportation a bus? Because it had a lot of data.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why was the math book upset? Because it was having a negative number of pages.",
  "Why was the math book happy? Because it had lots of solutions.",
  "Why couldn't the bicycle stand up by itself? Because it was two-tired.",
  "Why do statisticians enjoy spending time with their data? Because they're data-driven individuals.",
  "Why do statisticians like playing with their data? Because they have mean jokes.",
  "Why do statisticians have a tough time at parties? Because they're always trying to fit in."
)
