# Nginx with sticky module
# More detail about sticky module: https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/overview
FROM nginx:1.31-alpine


# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf


